version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: GroceryBooking
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_ROOT_HOST: root
    ports:
      - '3306:3306'

  assessment_app:
    container_name: assessment_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/GroceryBooking
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql-db